In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tnrange,tqdm_notebook
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
from sklearn.cluster import KMeans
from pandas.plotting import scatter_matrix
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.svm import SVC

#디렉토리 경로 
os.chdir("C:/Users/sora/Tobigs/week1/regression/assignment/Auction_master")

In [2]:
#데이터 불러오기
AM_train = pd.read_csv("Auction_master_train.csv")
AM_train.columns

Index(['Auction_key', 'Auction_class', 'Bid_class', 'Claim_price',
       'Appraisal_company', 'Appraisal_date', 'Auction_count',
       'Auction_miscarriage_count', 'Total_land_gross_area',
       'Total_land_real_area', 'Total_land_auction_area',
       'Total_building_area', 'Total_building_auction_area',
       'Total_appraisal_price', 'Minimum_sales_price', 'First_auction_date',
       'Final_auction_date', 'Final_result', 'Creditor', 'addr_do', 'addr_si',
       'addr_dong', 'addr_li', 'addr_san', 'addr_bunji1', 'addr_bunji2',
       'addr_etc', 'Apartment_usage', 'Preserve_regist_date', 'Total_floor',
       'Current_floor', 'Specific', 'Share_auction_YorN', 'road_name',
       'road_bunji1', 'road_bunji2', 'Close_date', 'Close_result', 'point.y',
       'point.x', 'Hammer_price'],
      dtype='object')

In [3]:
# 데이터 shape, 행1933개 , 열 41개
print(AM_train.shape)

(1933, 41)

In [4]:
train=AM_train

In [5]:
# 데이터 형태보기 
#object type 21, int 9, float 11개
#object 거래종류, 경매 종류,날짜 
#int 가격과, 거래 횟수
#float 도로명, 위도, 면적, 
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1933 entries, 0 to 1932
Data columns (total 41 columns):
Auction_key                    1933 non-null int64
Auction_class                  1933 non-null object
Bid_class                      1933 non-null object
Claim_price                    1933 non-null int64
Appraisal_company              1933 non-null object
Appraisal_date                 1933 non-null object
Auction_count                  1933 non-null int64
Auction_miscarriage_count      1933 non-null int64
Total_land_gross_area          1933 non-null float64
Total_land_real_area           1933 non-null float64
Total_land_auction_area        1933 non-null float64
Total_building_area            1933 non-null float64
Total_building_auction_area    1933 non-null float64
Total_appraisal_price          1933 non-null int64
Minimum_sales_price            1933 non-null int64
First_auction_date             1933 non-null object
Final_auction_date             1933 non-null object
Final_result                   1933 non-null object
Creditor                       1933 non-null object
addr_do                        1933 non-null object
addr_si                        1933 non-null object
addr_dong                      1933 non-null object
addr_li                        23 non-null object
addr_san                       1933 non-null object
addr_bunji1                    1929 non-null float64
addr_bunji2                    889 non-null float64
addr_etc                       1933 non-null object
Apartment_usage                1933 non-null object
Preserve_regist_date           1933 non-null object
Total_floor                    1933 non-null int64
Current_floor                  1933 non-null int64
Specific                       64 non-null object
Share_auction_YorN             1933 non-null object
road_name                      1933 non-null object
road_bunji1                    1909 non-null float64
road_bunji2                    155 non-null float64
Close_date                     1933 non-null object
Close_result                   1933 non-null object
point.y                        1933 non-null float64
point.x                        1933 non-null float64
Hammer_price                   1933 non-null int64
dtypes: float64(11), int64(9), object(21)
memory usage: 619.2+ KB

# 1. 데이터 전처리<br>
- 결측치 처리 <br>
- 파생변수 추가 <br>
- 더미변수화 <br>
- 정규화 <br>

In [6]:
#결측치가 많아 제거해야하는변수
# 일단 3개 지우고 시작 분석에 필요 없다고 판단
#주소_리
del train['addr_li']

In [7]:
#기타특이사항
del train['Specific']

In [8]:
del train['road_bunji2']

## 1-1)날짜 변수 처리 
-경매 분석상 날짜 데이터가 많으니 오늘날짜 기준 며칠이 지났는지 계산하는 함수 정의

In [9]:

def change_datetime(x):
    today = datetime.date.today()
    someday = datetime.date(int(x[:4]), int(x[5:7]), int(x[8:10]))
    diff = today - someday
    return diff.days

In [10]:
train["Appraisal_date"] = train["Appraisal_date"].apply(lambda x : x[:10])
train["First_auction_date"] =train["First_auction_date"].apply(lambda x : x[:10])
train["Final_auction_date"] =train["Final_auction_date"].apply(lambda x : x[:10])
train["Preserve_regist_date"] =train["Preserve_regist_date"].apply(lambda x : x[:10])
train["Close_date"] = train["Close_date"].apply(lambda x : x[:10])
train["Appraisal_date"] = train["Appraisal_date"].apply(change_datetime)
train["First_auction_date"] = train["First_auction_date"].apply(change_datetime)
train["Final_auction_date"] =train["Final_auction_date"].apply(change_datetime)
train["Preserve_regist_date"] = train["Preserve_regist_date"].apply(change_datetime)
train["Close_date"] = train["Close_date"].apply(change_datetime)

## 1-2) 파생변수 추가
- Diff_price : 최종 낙찰가- 최소 낙찰가 
- Diff_date : 최초경매일- 최종경매일

In [11]:
#최종 낙찰가와 최소 낙찰가를 뺀  Diff_price 변수 추가
train["Diff_price"] = train['Total_appraisal_price'] - train['Minimum_sales_price']
train["Diff_date"] =train['First_auction_date'] - train['Final_auction_date']

In [12]:
print(train.Auction_class.unique())
# 경매 구분을 0,1로 구분 
train.Auction_class.replace({'임의':0, '강제':1},inplace=True)
print(train.Auction_class.unique())
# 경매 주소를 크게 부산 서울 0,1 로 구분
print(train.addr_do.unique())
train.addr_do.replace({'부산':0, '서울':1},inplace=True)
#print(AM_train.addr_do.unique())

#아파트 주거 형태를 0,1 로 구분 
print(train.Apartment_usage.unique())
train.Apartment_usage.replace({'주상복합':0, '아파트':1},inplace=True)
print(train.Apartment_usage.unique())


#del AM_train1['addr_do']
#del AM_train2['addr_do']
#AM_train.index = np.arange(len(AM_train))

['임의' '강제']
[0 1]
['부산' '서울']
['주상복합' '아파트']
[0 1]

## 1-3) 변수 처리

In [13]:
#범주형 변수 처리
categorical=list(train.select_dtypes(include="object").columns)

In [14]:
categorical

['Bid_class',
 'Appraisal_company',
 'Final_result',
 'Creditor',
 'addr_si',
 'addr_dong',
 'addr_san',
 'addr_etc',
 'Share_auction_YorN',
 'road_name',
 'Close_result']

In [15]:
for col in categorical:
    print(col+ ": ",len(set(train[str(col)])))

Bid_class:  3
Appraisal_company:  238
Final_result:  1
Creditor:  448
addr_si:  39
addr_dong:  285
addr_san:  2
addr_etc:  1929
Share_auction_YorN:  2
road_name:  1038
Close_result:  2

In [16]:
# value값이 너무 많은 변수는 더미변수화 하기 힘듦
# 그만큼 값어치가 없다고 판단되는 변수들은 삭제한다.
del train['Appraisal_company']
del train['Creditor']
del train['addr_etc']
del train['road_name']
del train['addr_si']
del train['addr_dong']

In [17]:
del train['Auction_key']

In [18]:
train['Bid_class'].unique
train['Bid_class'].value_counts()
# 입찰 구분
train.Bid_class.replace({'일반':0, '개별':1, '일괄':2},inplace=True)

In [19]:
# 그 외의 결과에 필요 없다고 판단되는 변수 삭제
del train['Final_result']

In [20]:
#지분 경매 여분
set(train['Share_auction_YorN'])
train.Share_auction_YorN.replace({'N':0, 'Y':1},inplace=True)

## 최종 정리된 변수

In [21]:
train.columns

Index(['Auction_class', 'Bid_class', 'Claim_price', 'Appraisal_date',
       'Auction_count', 'Auction_miscarriage_count', 'Total_land_gross_area',
       'Total_land_real_area', 'Total_land_auction_area',
       'Total_building_area', 'Total_building_auction_area',
       'Total_appraisal_price', 'Minimum_sales_price', 'First_auction_date',
       'Final_auction_date', 'addr_do', 'addr_san', 'addr_bunji1',
       'addr_bunji2', 'Apartment_usage', 'Preserve_regist_date', 'Total_floor',
       'Current_floor', 'Share_auction_YorN', 'road_bunji1', 'Close_date',
       'Close_result', 'point.y', 'point.x', 'Hammer_price', 'Diff_price',
       'Diff_date'],
      dtype='object')

### label 과 연속변수들간 correlation

In [22]:
cor_matrix=train.corr()
corr=abs(cor_matrix['Hammer_price']).sort_values(ascending=False)

In [23]:
corr

Hammer_price                   1.000000
Minimum_sales_price            0.994592
Total_appraisal_price          0.953464
Total_building_auction_area    0.772839
Total_building_area            0.768454
Diff_price                     0.747443
Total_land_auction_area        0.700639
Total_land_real_area           0.696099
addr_do                        0.306488
point.x                        0.296312
point.y                        0.295698
Claim_price                    0.267728
Total_floor                    0.220830
Current_floor                  0.198013
Bid_class                      0.131107
Share_auction_YorN             0.091157
Preserve_regist_date           0.074827
Total_land_gross_area          0.070466
Auction_class                  0.054813
road_bunji1                    0.020404
Appraisal_date                 0.020075
Auction_count                  0.016999
Diff_date                      0.015686
First_auction_date             0.012063
Auction_miscarriage_count      0.011296
Apartment_usage                0.004344
Final_auction_date             0.004150
addr_bunji2                    0.003641
addr_bunji1                    0.003139
Close_date                     0.000111
Name: Hammer_price, dtype: float64

In [24]:
# 상관 계수가 낮은 15개 feature 삭제
low_corr=corr.tail(15).index

train.drop(list(low_corr),axis=1,inplace=True)

In [26]:
train.columns

Index(['Bid_class', 'Claim_price', 'Total_land_real_area',
       'Total_land_auction_area', 'Total_building_area',
       'Total_building_auction_area', 'Total_appraisal_price',
       'Minimum_sales_price', 'addr_do', 'addr_san', 'Total_floor',
       'Current_floor', 'Close_result', 'point.y', 'point.x', 'Hammer_price',
       'Diff_price'],
      dtype='object')

In [27]:
#19 개로 줄은 변수
len(train.columns)

17

In [28]:
train

,Bid_class,Claim_price,Total_land_real_area,Total_land_auction_area,Total_building_area,Total_building_auction_area,Total_appraisal_price,Minimum_sales_price,addr_do,addr_san,Total_floor,Current_floor,Close_result,point.y,point.x,Hammer_price,Diff_price
0,1,1766037301,37.35,37.35,181.77,181.77,836000000,668800000,0,N,45,5,배당,35.162717,129.137048,760000000,167200000
1,0,152946867,18.76,18.76,118.38,118.38,1073000000,858400000,0,N,70,51,배당,35.156633,129.145068,971889999,214600000
2,1,11326510,71.00,71.00,49.94,49.94,119000000,76160000,0,N,15,14,배당,35.184601,128.996765,93399999,42840000
3,0,183581724,32.98,32.98,84.91,84.91,288400000,230720000,0,N,20,11,배당,35.154180,129.089081,256899000,57680000
4,0,45887671,45.18,45.18,84.96,84.96,170000000,136000000,0,N,7,7,배당,35.099630,128.998874,158660000,34000000
5,0,105437195,41.39,41.39,84.46,84.46,222000000,177600000,0,N,20,17,배당,35.086933,129.065706,206989000,44400000
6,0,137548730,81.77,81.77,112.70,112.70,188000000,120320000,0,N,6,6,배당,35.084049,129.070231,135500000,67680000
7,0,506916971,92.22,92.22,243.35,243.35,667000000,533600000,0,N,24,13,배당,35.127808,129.112206,640299999,133400000
8,0,40782876,66.44,66.44,67.21,67.21,94000000,75200000,0,N,3,1,배당,35.080817,129.020155,77380000,18800000
9,0,150000000,78.52,78.52,84.92,84.92,163000000,130400000,0,N,5,4,배당,35.187903,129.130913,177070000,32600000
10,1,500000000,18.27,18.27,81.96,81.96,299000000,239200000,0,N,15,12,배당,35.176581,129.071228,240000001,59800000
11,0,37122950,37.38,37.38,84.72,84.72,241000000,192800000,0,N,15,2,배당,35.071897,129.076585,221017200,48200000
12,0,25000000,31.69,7.04,84.60,18.80,41000000,26240000,0,N,22,11,배당,35.098222,128.965136,31888000,14760000
13,0,135000000,0.00,0.00,106.34,106.34,560000000,448000000,0,N,39,5,배당,35.161948,129.179110,518800000,112000000
14,0,953680000,80.62,80.62,182.76,182.76,669000000,669000000,0,N,28,26,배당,35.188580,129.089335,670190000,0
15,0,13848484,53.84,53.84,150.80,150.80,604000000,483200000,0,N,31,8,배당,35.159833,129.131154,531100000,120800000
16,0,149393725,25.70,25.70,74.45,74.45,165000000,105600000,0,N,21,1,배당,35.191666,129.126864,143999000,59400000
17,1,1046685025,7.59,7.59,43.63,43.63,160000000,128000000,0,N,14,12,배당,35.216645,129.079149,133000000,32000000
18,0,42479480,41.69,41.69,83.84,83.84,149000000,119200000,0,N,9,4,배당,35.081003,129.068091,126651100,29800000
19,0,30665922,39.43,39.43,62.97,62.97,90000000,72000000,0,N,6,5,배당,35.132840,129.042040,73899900,18000000
20,0,160000000,5.66,5.66,53.29,53.29,206000000,206000000,0,N,29,25,배당,35.218631,129.084142,206119000,0
21,0,45589041,30.87,15.44,59.99,30.00,63000000,50400000,0,N,10,9,배당,35.090638,129.050729,60299000,12600000
22,0,122134370,20.60,20.60,59.67,59.67,145000000,116000000,0,N,12,2,배당,35.191666,129.126864,136630000,29000000
23,0,19800000,39.80,39.80,117.59,117.59,352000000,281600000,0,N,19,1,배당,35.104126,129.016082,362000000,70400000
24,0,122663013,17.93,17.93,49.78,49.78,151000000,120800000,0,N,9,6,배당,35.217180,129.080055,122000000,30200000
25,0,120000000,18.41,18.41,124.26,124.26,354000000,354000000,0,N,35,22,배당,35.188590,129.081886,371131000,0
26,0,311657509,59.64,59.64,138.56,138.56,350000000,280000000,0,N,16,9,배당,35.101297,128.957386,342750000,70000000
27,0,135600000,31.77,31.77,84.72,84.72,192000000,153600000,0,N,16,4,배당,35.112673,129.029836,173711110,38400000
28,0,51975561,74.49,74.49,84.99,84.99,354000000,283200000,0,N,10,2,배당,35.080855,128.897144,342525000,70800000
29,1,1087000000,16.65,16.65,98.08,98.08,228745632,117118000,0,N,15,8,배당,35.201112,129.088687,126630000,111627632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,0,179747997,40.52,40.52,84.15,84.15,334000000,267200000,1,N,15,5,배당,37.460751,126.927965,301554999,66800000
1904,0,414554884,40.34,40.34,84.81,84.81,670000000,670000000,1,N,33,6,배당,37.555508,127.141592,683800000,0
1905,0,1107295474,123.04,123.04,164.45,164.45,1600000000,1280000000,1,N,15,8,배당,37.517915,127.136104,1605699900,320000000
1906,0,200000000,33.06,3.67,177.62,19.74,111000000,71040000,1,N,19,11,배당,37.518053,126.978721,92100000,39960000
1907,0,62619025,25.47,4.63,39.84,7.24,38100000,30480000,1,N,12,2,배당,37.616441,127.085118,36300000,7620000
1908,0,290729614,49.97,49.97,113.51,113.51,500000000,400000000,1,N,18,9,배당,37.635760,127.061619,510000000,100000000
1909,0,386591869,40.27,40.27,84.94,84.94,594000000,594000000,1,N,20,6,배당,37.550916,126.959559,660530000,0
1910,0,2000000000,108.25,108.25,134.49,134.49,1540000000,1540000000,1,N,18,2,배당,37.507444,127.076709,1561800000,0
1911,0,56320487,78.55,8.73,130.93,14.55,94000000,75200000,1,N,14,3,배당,37.506599,127.126942,91300000,18800000
1912,0,357918375,60.13,60.13,121.27,121.27,940000000,752000000,1,N,9,2,배당,37.479785,126.995602,920500000,188000000
1913,0,390208900,58.09,58.09,84.65,84.65,470000000,376000000,1,N,10,6,배당,37.623938,127.088456,444266000,94000000
1914,0,200000,46.71,46.71,114.34,114.34,643000000,514400000,1,N,6,4,배당,37.484647,127.024026,660015000,128600000
1915,0,340000000,43.05,10.89,84.79,21.44,96000000,96000000,1,N,13,2,배당,37.564718,126.927328,101600000,0
1916,0,140000000,27.01,27.01,56.82,56.82,182000000,145600000,1,N,6,3,배당,37.664210,127.036104,171220000,36400000
1917,1,1056427163,7.25,7.25,12.77,12.77,90000000,72000000,1,Y,8,7,배당,37.534208,126.844878,83699000,18000000
1918,0,500000000,86.08,86.08,153.71,153.71,1170000000,1170000000,1,N,13,4,배당,37.490765,127.042146,1200000000,0
1919,0,399507027,44.67,44.67,84.91,84.91,411000000,411000000,1,N,15,3,배당,37.636708,127.066352,432700000,0
1920,0,213523555,45.83,45.83,99.68,99.68,370000000,296000000,1,N,5,2,배당,37.610067,126.917732,337180000,74000000
1921,0,8901332,23.42,23.42,58.42,58.42,405000000,324000000,1,N,21,16,배당,37.567310,127.072777,400100000,81000000
1922,0,348000000,60.99,60.99,126.65,126.65,830000000,830000000,1,N,17,7,배당,37.555565,126.840208,832100000,0
1923,0,51228630,57.58,57.58,59.49,59.49,270000000,270000000,1,N,12,11,배당,37.516755,126.834373,300015000,0
1924,0,178831561,34.90,34.90,84.50,84.50,439000000,439000000,1,N,25,23,,37.661182,127.046189,453616100,0
1925,0,34880583,30.16,6.70,59.98,13.33,92900000,92900000,1,N,17,12,배당,37.659027,127.074355,95655000,0
1926,0,252000000,48.04,48.04,84.37,84.37,451000000,360800000,1,N,15,3,배당,37.591237,126.923704,455588000,90200000
1927,0,140000000,33.13,33.13,67.62,67.62,330000000,264000000,1,N,7,5,배당,37.492847,126.888545,295899500,66000000
1928,0,280000000,40.55,40.55,84.87,84.87,401000000,401000000,1,N,21,15,배당,37.648810,127.048683,402500000,0
1929,0,200000000,39.60,39.60,114.81,114.81,454000000,363200000,1,N,23,23,배당,37.663291,127.077063,430234600,90800000
1930,0,354805459,19.03,19.03,133.98,133.98,1285000000,1028000000,1,N,32,19,배당,37.558319,126.981994,1118999990,257000000
1931,0,80000000,42.20,42.20,84.94,84.94,407000000,325600000,1,N,15,11,배당,37.647061,127.028002,403000000,81400000
1932,0,180000000,45.68,45.68,102.92,102.92,750000000,600000000,1,N,22,7,배당,37.566255,126.848961,686010000,150000000

In [29]:
#추가로 위도 경도에 대한 데이터도 지운다 (부산 ,서울로 충분히 설명됌)
del train['point.y']
del train['point.x']

In [30]:
len(set('Close_result'))

9

In [31]:
train['Close_result']

0         배당
1         배당
2         배당
3         배당
4         배당
5         배당
6         배당
7         배당
8         배당
9         배당
10        배당
11        배당
12        배당
13        배당
14        배당
15        배당
16        배당
17        배당
18        배당
19        배당
20        배당
21        배당
22        배당
23        배당
24        배당
25        배당
26        배당
27        배당
28        배당
29        배당
        ...
1903      배당
1904      배당
1905      배당
1906      배당
1907      배당
1908      배당
1909      배당
1910      배당
1911      배당
1912      배당
1913      배당
1914      배당
1915      배당
1916      배당
1917      배당
1918      배당
1919      배당
1920      배당
1921      배당
1922      배당
1923      배당
1924
1925      배당
1926      배당
1927      배당
1928      배당
1929      배당
1930      배당
1931      배당
1932      배당
Name: Close_result, Length: 1933, dtype: object

In [32]:
del train['Close_result']

In [33]:
train

,Bid_class,Claim_price,Total_land_real_area,Total_land_auction_area,Total_building_area,Total_building_auction_area,Total_appraisal_price,Minimum_sales_price,addr_do,addr_san,Total_floor,Current_floor,Hammer_price,Diff_price
0,1,1766037301,37.35,37.35,181.77,181.77,836000000,668800000,0,N,45,5,760000000,167200000
1,0,152946867,18.76,18.76,118.38,118.38,1073000000,858400000,0,N,70,51,971889999,214600000
2,1,11326510,71.00,71.00,49.94,49.94,119000000,76160000,0,N,15,14,93399999,42840000
3,0,183581724,32.98,32.98,84.91,84.91,288400000,230720000,0,N,20,11,256899000,57680000
4,0,45887671,45.18,45.18,84.96,84.96,170000000,136000000,0,N,7,7,158660000,34000000
5,0,105437195,41.39,41.39,84.46,84.46,222000000,177600000,0,N,20,17,206989000,44400000
6,0,137548730,81.77,81.77,112.70,112.70,188000000,120320000,0,N,6,6,135500000,67680000
7,0,506916971,92.22,92.22,243.35,243.35,667000000,533600000,0,N,24,13,640299999,133400000
8,0,40782876,66.44,66.44,67.21,67.21,94000000,75200000,0,N,3,1,77380000,18800000
9,0,150000000,78.52,78.52,84.92,84.92,163000000,130400000,0,N,5,4,177070000,32600000
10,1,500000000,18.27,18.27,81.96,81.96,299000000,239200000,0,N,15,12,240000001,59800000
11,0,37122950,37.38,37.38,84.72,84.72,241000000,192800000,0,N,15,2,221017200,48200000
12,0,25000000,31.69,7.04,84.60,18.80,41000000,26240000,0,N,22,11,31888000,14760000
13,0,135000000,0.00,0.00,106.34,106.34,560000000,448000000,0,N,39,5,518800000,112000000
14,0,953680000,80.62,80.62,182.76,182.76,669000000,669000000,0,N,28,26,670190000,0
15,0,13848484,53.84,53.84,150.80,150.80,604000000,483200000,0,N,31,8,531100000,120800000
16,0,149393725,25.70,25.70,74.45,74.45,165000000,105600000,0,N,21,1,143999000,59400000
17,1,1046685025,7.59,7.59,43.63,43.63,160000000,128000000,0,N,14,12,133000000,32000000
18,0,42479480,41.69,41.69,83.84,83.84,149000000,119200000,0,N,9,4,126651100,29800000
19,0,30665922,39.43,39.43,62.97,62.97,90000000,72000000,0,N,6,5,73899900,18000000
20,0,160000000,5.66,5.66,53.29,53.29,206000000,206000000,0,N,29,25,206119000,0
21,0,45589041,30.87,15.44,59.99,30.00,63000000,50400000,0,N,10,9,60299000,12600000
22,0,122134370,20.60,20.60,59.67,59.67,145000000,116000000,0,N,12,2,136630000,29000000
23,0,19800000,39.80,39.80,117.59,117.59,352000000,281600000,0,N,19,1,362000000,70400000
24,0,122663013,17.93,17.93,49.78,49.78,151000000,120800000,0,N,9,6,122000000,30200000
25,0,120000000,18.41,18.41,124.26,124.26,354000000,354000000,0,N,35,22,371131000,0
26,0,311657509,59.64,59.64,138.56,138.56,350000000,280000000,0,N,16,9,342750000,70000000
27,0,135600000,31.77,31.77,84.72,84.72,192000000,153600000,0,N,16,4,173711110,38400000
28,0,51975561,74.49,74.49,84.99,84.99,354000000,283200000,0,N,10,2,342525000,70800000
29,1,1087000000,16.65,16.65,98.08,98.08,228745632,117118000,0,N,15,8,126630000,111627632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,0,179747997,40.52,40.52,84.15,84.15,334000000,267200000,1,N,15,5,301554999,66800000
1904,0,414554884,40.34,40.34,84.81,84.81,670000000,670000000,1,N,33,6,683800000,0
1905,0,1107295474,123.04,123.04,164.45,164.45,1600000000,1280000000,1,N,15,8,1605699900,320000000
1906,0,200000000,33.06,3.67,177.62,19.74,111000000,71040000,1,N,19,11,92100000,39960000
1907,0,62619025,25.47,4.63,39.84,7.24,38100000,30480000,1,N,12,2,36300000,7620000
1908,0,290729614,49.97,49.97,113.51,113.51,500000000,400000000,1,N,18,9,510000000,100000000
1909,0,386591869,40.27,40.27,84.94,84.94,594000000,594000000,1,N,20,6,660530000,0
1910,0,2000000000,108.25,108.25,134.49,134.49,1540000000,1540000000,1,N,18,2,1561800000,0
1911,0,56320487,78.55,8.73,130.93,14.55,94000000,75200000,1,N,14,3,91300000,18800000
1912,0,357918375,60.13,60.13,121.27,121.27,940000000,752000000,1,N,9,2,920500000,188000000
1913,0,390208900,58.09,58.09,84.65,84.65,470000000,376000000,1,N,10,6,444266000,94000000
1914,0,200000,46.71,46.71,114.34,114.34,643000000,514400000,1,N,6,4,660015000,128600000
1915,0,340000000,43.05,10.89,84.79,21.44,96000000,96000000,1,N,13,2,101600000,0
1916,0,140000000,27.01,27.01,56.82,56.82,182000000,145600000,1,N,6,3,171220000,36400000
1917,1,1056427163,7.25,7.25,12.77,12.77,90000000,72000000,1,Y,8,7,83699000,18000000
1918,0,500000000,86.08,86.08,153.71,153.71,1170000000,1170000000,1,N,13,4,1200000000,0
1919,0,399507027,44.67,44.67,84.91,84.91,411000000,411000000,1,N,15,3,432700000,0
1920,0,213523555,45.83,45.83,99.68,99.68,370000000,296000000,1,N,5,2,337180000,74000000
1921,0,8901332,23.42,23.42,58.42,58.42,405000000,324000000,1,N,21,16,400100000,81000000
1922,0,348000000,60.99,60.99,126.65,126.65,830000000,830000000,1,N,17,7,832100000,0
1923,0,51228630,57.58,57.58,59.49,59.49,270000000,270000000,1,N,12,11,300015000,0
1924,0,178831561,34.90,34.90,84.50,84.50,439000000,439000000,1,N,25,23,453616100,0
1925,0,34880583,30.16,6.70,59.98,13.33,92900000,92900000,1,N,17,12,95655000,0
1926,0,252000000,48.04,48.04,84.37,84.37,451000000,360800000,1,N,15,3,455588000,90200000
1927,0,140000000,33.13,33.13,67.62,67.62,330000000,264000000,1,N,7,5,295899500,66000000
1928,0,280000000,40.55,40.55,84.87,84.87,401000000,401000000,1,N,21,15,402500000,0
1929,0,200000000,39.60,39.60,114.81,114.81,454000000,363200000,1,N,23,23,430234600,90800000
1930,0,354805459,19.03,19.03,133.98,133.98,1285000000,1028000000,1,N,32,19,1118999990,257000000
1931,0,80000000,42.20,42.20,84.94,84.94,407000000,325600000,1,N,15,11,403000000,81400000
1932,0,180000000,45.68,45.68,102.92,102.92,750000000,600000000,1,N,22,7,686010000,150000000

In [34]:
#나머지는 더미 변수화
#주소가 경매에 중요하다고 생각함. 
train_d = pd.get_dummies(train)

In [35]:
y=train_d.Hammer_price
# hammer_price 의 median 값을 확용해 0,1 로 categorical 변수화하기
y1=np.array(y)
median_y=np.median(y1)
median_y

354450000.0

## hameer_price를 더미화 하는 함수

In [36]:
def d_hammer(x):
    if(x>=median_y):
        return 1
    else:
        return 0

In [37]:
train_d['Hammer_price']=train_d['Hammer_price'].apply(d_hammer)

In [38]:
train_d['Hammer_price']

0       1
1       1
2       0
3       0
4       0
5       0
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      1
14      1
15      1
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      1
24      0
25      1
26      0
27      0
28      0
29      0
       ..
1903    0
1904    1
1905    1
1906    0
1907    0
1908    1
1909    1
1910    1
1911    0
1912    1
1913    1
1914    1
1915    0
1916    0
1917    0
1918    1
1919    1
1920    0
1921    1
1922    1
1923    0
1924    1
1925    0
1926    1
1927    0
1928    1
1929    1
1930    1
1931    1
1932    1
Name: Hammer_price, Length: 1933, dtype: int64

## 연속형 변수 처리

In [39]:
train_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1933 entries, 0 to 1932
Data columns (total 15 columns):
Bid_class                      1933 non-null int64
Claim_price                    1933 non-null int64
Total_land_real_area           1933 non-null float64
Total_land_auction_area        1933 non-null float64
Total_building_area            1933 non-null float64
Total_building_auction_area    1933 non-null float64
Total_appraisal_price          1933 non-null int64
Minimum_sales_price            1933 non-null int64
addr_do                        1933 non-null int64
Total_floor                    1933 non-null int64
Current_floor                  1933 non-null int64
Hammer_price                   1933 non-null int64
Diff_price                     1933 non-null int64
addr_san_N                     1933 non-null uint8
addr_san_Y                     1933 non-null uint8
dtypes: float64(4), int64(9), uint8(2)
memory usage: 200.2 KB

In [40]:
numeric=list(['Claim_price','Total_land_real_area','Total_land_auction_area','Total_building_area','Total_building_auction_area','Total_appraisal_price'
,'Minimum_sales_price','Total_floor','Current_floor','Diff_price'])

In [41]:
numeric

['Claim_price',
 'Total_land_real_area',
 'Total_land_auction_area',
 'Total_building_area',
 'Total_building_auction_area',
 'Total_appraisal_price',
 'Minimum_sales_price',
 'Total_floor',
 'Current_floor',
 'Diff_price']

In [42]:
train_z=train_d
train_z[numeric]= (train_z[numeric] - train_z[numeric].mean())/(train_z[numeric].max() - train_z[numeric].min())

In [43]:
y=train_d['Hammer_price']

y

0       1
1       1
2       0
3       0
4       0
5       0
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      1
14      1
15      1
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      1
24      0
25      1
26      0
27      0
28      0
29      0
       ..
1903    0
1904    1
1905    1
1906    0
1907    0
1908    1
1909    1
1910    1
1911    0
1912    1
1913    1
1914    1
1915    0
1916    0
1917    0
1918    1
1919    1
1920    0
1921    1
1922    1
1923    0
1924    1
1925    0
1926    1
1927    0
1928    1
1929    1
1930    1
1931    1
1932    1
Name: Hammer_price, Length: 1933, dtype: int64

In [44]:
del train_d['Hammer_price']

In [45]:
x=train_z

## 분류 모델
- svm
- 로지스틱 회귀
- knn
- 나이브베이지

## svm

In [46]:
y=np.array(y)
x=np.array(x)

In [47]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

def fivefold(x,y,model):
    model_scores = np.zeros(5)
    scores = np.zeros(5)

    cv = KFold(5, shuffle=True, random_state=0)
    for i, (idx_train, idx_test) in enumerate(cv.split(x)):
        #데이터 하나씩 트레인과 테스트에 부과
        x_train = x[idx_train]
        x_test = x[idx_test]
        y_train = y[idx_train]
        y_test = y[idx_test]

        #모델 fit
        result = model.fit(x_train,y_train)

        #prediction
        model_pred = result.predict(x_train)
        pred = result.predict(x_test)
        model_accuracy = accuracy_score(y_train, model_pred)
        accuracy= accuracy_score(y_test, pred)

        #test 5번 하나하나 프린트
        model_scores[i] = model_accuracy
        scores[i] = accuracy
        print("학습 accuacy = {:.8f}, 검증 accuacy = {:.8f}".format(model_accuracy,accuracy))
    print('평균 train accuacy : ' + str(model_scores.mean()) )
    print('평균 test accuacy : ' + str(scores.mean()) )

In [48]:
x

array([[ 1.00000000e+00,  6.10390529e-02, -1.86950544e-03, ...,
         6.30330891e-03,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -9.50997876e-03, -8.84291720e-03, ...,
         9.80037993e-03,  1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00, -1.57037909e-02,  1.07531576e-02, ...,
        -2.87170696e-03,  1.00000000e+00,  0.00000000e+00],
       ...,
       [ 0.00000000e+00, -6.81627972e-04, -8.74163580e-03, ...,
         1.29285616e-02,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.27003336e-02, -5.01914517e-05, ...,
        -2.68323041e-05,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -8.32680124e-03,  1.25521322e-03, ...,
         5.03432955e-03,  1.00000000e+00,  0.00000000e+00]])

In [49]:
rbf_kernel_svm_clf = SVC(kernel="rbf",C=0.001,gamma=0.5)

rbf_kernel_svm_clf.fit(x, y)

SVC(C=0.001, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [50]:
# 최적의 C 와 gamma 를 찾기 위해 grid search 수행
from sklearn.model_selection import GridSearchCV
values={'C':[0.001,0.1,1,10],'gamma':[0.5,5,10,50]}

In [51]:
grid_search=GridSearchCV(estimator=rbf_kernel_svm_clf,param_grid=values,cv=5)

In [52]:
grid_search

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=SVC(C=0.001, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.001, 0.1, 1, 10], 'gamma': [0.5, 5, 10, 50]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [53]:

# 그리디 서치 적용 (최적의 파라미터 찾기 위함)
grid_search.fit(x,y)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=SVC(C=0.001, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'C': [0.001, 0.1, 1, 10], 'gamma': [0.5, 5, 10, 50]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [54]:
grid_search.best_score_

0.8810139679255043

In [55]:
# 최적의 paramator 는  c=10 과 gamma 50.
grid_search.best_params_

{'C': 10, 'gamma': 50}

In [56]:
rbf_kernel_svm_clf = SVC(kernel="rbf",C=10,gamma=50)

rbf_kernel_svm_clf.fit(x, y)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=50, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [57]:
# 5 교차 검증을 한 정확도

fivefold(x,y,rbf_kernel_svm_clf)

학습 accuacy = 0.96701164, 검증 accuacy = 0.94832041
학습 accuacy = 0.96248383, 검증 accuacy = 0.95865633
학습 accuacy = 0.96571798, 검증 accuacy = 0.94056848
학습 accuacy = 0.96832579, 검증 accuacy = 0.93782383
학습 accuacy = 0.96509373, 검증 accuacy = 0.94041451
평균 train accuacy : 0.9657265951459696
평균 test accuacy : 0.9451567123214308

In [58]:
# 정확도가 0.95정도로 높은 편이다.

## logistic regreesion

In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics # 모델의 평가를 위해서 씁니다
from sklearn.model_selection import train_test_split # traning set을 쉽게 나눠주는 함수입니다.

In [60]:
logistic =LogisticRegression()

logistic.fit(x, y)

C:\Users\sora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [61]:
fivefold(x,y,logistic)

C:\Users\sora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

학습 accuacy = 0.79301423, 검증 accuacy = 0.77002584

C:\Users\sora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

학습 accuacy = 0.78913325, 검증 accuacy = 0.79844961

C:\Users\sora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

학습 accuacy = 0.79754204, 검증 accuacy = 0.77002584

C:\Users\sora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

학습 accuacy = 0.78862314, 검증 accuacy = 0.79533679

C:\Users\sora\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

학습 accuacy = 0.78280543, 검증 accuacy = 0.81088083
평균 train accuacy : 0.7902236185547957
평균 test accuacy : 0.7889437817139949

## knn

In [62]:
from sklearn.neighbors import KNeighborsClassifier as knn

In [63]:
knn_model=knn(n_neighbors=5)
knn_model.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [64]:
fivefold(x,y,knn_model)

학습 accuacy = 0.92108668, 검증 accuacy = 0.87855297
학습 accuacy = 0.92238034, 검증 accuacy = 0.88372093
학습 accuacy = 0.91914618, 검증 accuacy = 0.88113695
학습 accuacy = 0.92178410, 검증 accuacy = 0.86528497
학습 accuacy = 0.92049127, 검증 accuacy = 0.86787565
평균 train accuacy : 0.9209777134059912
평균 test accuacy : 0.8753142948949673

In [65]:
k={'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

In [66]:
grid_search=GridSearchCV(knn_model,param_grid=k,cv=5)

In [67]:
grid_search.fit(x,y)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [68]:
grid_search.best_score_

0.8303155716502846

In [69]:
grid_search.best_params_

{'n_neighbors': 6}

In [70]:
#최적의 paramator k=6으로 선정
knn_model=knn(n_neighbors=6)

In [71]:
fivefold(x,y,knn_model)

학습 accuacy = 0.91009056, 검증 accuacy = 0.87080103
학습 accuacy = 0.90491591, 검증 accuacy = 0.88372093
학습 accuacy = 0.90426908, 검증 accuacy = 0.87596899
학습 accuacy = 0.90562379, 검증 accuacy = 0.85492228
학습 accuacy = 0.90756303, 검증 accuacy = 0.86269430
평균 train accuacy : 0.9064924725985527
평균 test accuacy : 0.8696215072766463

In [72]:
# k=6으로 했을 때가 가장 정확도가 0.9 정도로 높았다.

# naive bayes

In [73]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer, HashingVectorizer, CountVectorizer

In [74]:
train_d

,Bid_class,Claim_price,Total_land_real_area,Total_land_auction_area,Total_building_area,Total_building_auction_area,Total_appraisal_price,Minimum_sales_price,addr_do,Total_floor,Current_floor,Diff_price,addr_san_N,addr_san_Y
0,1,0.061039,-0.001870,-0.001486,0.020103,0.020599,0.012194,0.017811,0,0.363885,-0.058737,0.006303,1,0
1,0,-0.009510,-0.008843,-0.008459,0.005173,0.005697,0.020728,0.031147,0,0.688560,0.648955,0.009800,1,0
2,1,-0.015704,0.010753,0.011137,-0.010947,-0.010393,-0.013624,-0.023876,0,-0.025725,0.079725,-0.002872,1,0
3,0,-0.008170,-0.003509,-0.003125,-0.002710,-0.002172,-0.007524,-0.013004,0,0.039210,0.033571,-0.001777,1,0
4,0,-0.014192,0.001068,0.001451,-0.002699,-0.002160,-0.011788,-0.019667,0,-0.129622,-0.027968,-0.003524,1,0
5,0,-0.011588,-0.000354,0.000030,-0.002816,-0.002278,-0.009915,-0.016741,0,0.039210,0.125878,-0.002757,1,0
6,0,-0.010183,0.014793,0.015177,0.003835,0.004361,-0.011140,-0.020770,0,-0.142609,-0.043352,-0.001039,1,0
7,0,0.005971,0.018713,0.019097,0.034607,0.035077,0.006109,0.008301,0,0.091158,0.064340,0.003810,1,0
8,0,-0.014416,0.009043,0.009426,-0.006879,-0.006333,-0.014525,-0.023944,0,-0.181570,-0.120275,-0.004645,1,0
9,0,-0.009639,0.013574,0.013958,-0.002708,-0.002170,-0.012040,-0.020061,0,-0.155596,-0.074122,-0.003627,1,0
10,1,0.005669,-0.009027,-0.008643,-0.003405,-0.002866,-0.007143,-0.012408,0,-0.025725,0.048955,-0.001620,1,0
11,0,-0.014576,-0.001858,-0.001474,-0.002755,-0.002217,-0.009231,-0.015672,0,-0.025725,-0.104891,-0.002476,1,0
12,0,-0.015106,-0.003993,-0.012856,-0.002783,-0.017714,-0.016433,-0.027388,0,0.065184,0.033571,-0.004943,1,0
13,0,-0.010295,-0.015880,-0.015496,0.002337,0.002866,0.002256,0.002279,0,0.285963,-0.058737,0.002231,1,0
14,0,0.025510,0.014362,0.014746,0.020337,0.020832,0.006181,0.017825,0,0.143106,0.264340,-0.006032,1,0
15,0,-0.015593,0.004316,0.004700,0.012809,0.013319,0.003840,0.004755,0,0.182067,-0.012583,0.002880,1,0
16,0,-0.009665,-0.006240,-0.005856,-0.005174,-0.004631,-0.011968,-0.021805,0,0.052197,-0.120275,-0.001650,1,0
17,1,0.029578,-0.013033,-0.012649,-0.012433,-0.011877,-0.012148,-0.020230,0,-0.038712,0.048955,-0.003671,1,0
18,0,-0.014341,-0.000242,0.000142,-0.002962,-0.002424,-0.012544,-0.020849,0,-0.103648,-0.074122,-0.003834,1,0
19,0,-0.014858,-0.001089,-0.000706,-0.007878,-0.007330,-0.014669,-0.024169,0,-0.142609,-0.058737,-0.004704,1,0
20,0,-0.009202,-0.013757,-0.013373,-0.010158,-0.009606,-0.010492,-0.014743,0,0.156093,0.248955,-0.006032,1,0
21,0,-0.014205,-0.004300,-0.009705,-0.008580,-0.015081,-0.015641,-0.025688,0,-0.090661,0.002802,-0.005103,1,0
22,0,-0.010858,-0.008153,-0.007769,-0.008655,-0.008106,-0.012688,-0.021074,0,-0.064686,-0.104891,-0.003893,1,0
23,0,-0.015333,-0.000950,-0.000567,0.004987,0.005511,-0.005234,-0.009425,0,0.026223,-0.120275,-0.000838,1,0
24,0,-0.010834,-0.009154,-0.008771,-0.010985,-0.010431,-0.012472,-0.020736,0,-0.103648,-0.043352,-0.003804,1,0
25,0,-0.010951,-0.008974,-0.008590,0.006558,0.007079,-0.005162,-0.004333,0,0.234015,0.202802,-0.006032,1,0
26,0,-0.002569,0.006492,0.006876,0.009926,0.010441,-0.005306,-0.009538,0,-0.012738,0.002802,-0.000868,1,0
27,0,-0.010269,-0.003963,-0.003579,-0.002755,-0.002217,-0.010996,-0.018429,0,-0.012738,-0.074122,-0.003199,1,0
28,0,-0.013926,0.012062,0.012446,-0.002692,-0.002153,-0.005162,-0.009313,0,-0.090661,-0.104891,-0.000809,1,0
29,1,0.031341,-0.009634,-0.009251,0.000392,0.000924,-0.009673,-0.020995,0,-0.025725,-0.012583,0.002203,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,0,-0.008338,-0.000680,-0.000297,-0.002889,-0.002351,-0.005882,-0.010438,1,-0.025725,-0.058737,-0.001104,1,0
1904,0,0.001932,-0.000748,-0.000364,-0.002734,-0.002196,0.006217,0.017895,1,0.208041,-0.043352,-0.006032,1,0
1905,0,0.032229,0.030274,0.030658,0.016024,0.016528,0.039705,0.060803,1,-0.025725,-0.012583,0.017577,1,0
1906,0,-0.007452,-0.003479,-0.014120,0.019126,-0.017493,-0.013912,-0.024236,1,0.026223,0.033571,-0.003084,1,0
1907,0,-0.013460,-0.006326,-0.013760,-0.013326,-0.020432,-0.016538,-0.027089,1,-0.064686,-0.104891,-0.005470,1,0
1908,0,-0.003484,0.002864,0.003248,0.004026,0.004552,0.000095,-0.001097,1,0.013236,0.002802,0.001345,1,0
1909,0,0.000709,-0.000774,-0.000390,-0.002703,-0.002165,0.003480,0.012549,1,0.039210,-0.043352,-0.006032,1,0
1910,0,0.071271,0.024726,0.025110,0.008967,0.009484,0.037545,0.079091,1,0.013236,-0.104891,-0.006032,1,0
1911,0,-0.013736,0.013585,-0.012222,0.008129,-0.018713,-0.014525,-0.023944,1,-0.038712,-0.089506,-0.004645,1,0
1912,0,-0.000545,0.006676,0.007059,0.005854,0.006376,0.015939,0.023663,1,-0.103648,-0.104891,0.007838,1,0
1913,0,0.000867,0.005910,0.006294,-0.002772,-0.002233,-0.000985,-0.002785,1,-0.090661,-0.043352,0.000903,1,0
1914,0,-0.016190,0.001642,0.002025,0.004221,0.004747,0.005244,0.006950,1,-0.142609,-0.074122,0.003455,1,0
1915,0,-0.001329,0.000269,-0.011411,-0.002739,-0.017094,-0.014453,-0.022481,1,-0.051699,-0.104891,-0.006032,1,0
1916,0,-0.010076,-0.005748,-0.005364,-0.009327,-0.008776,-0.011356,-0.018992,1,-0.142609,-0.089506,-0.003347,1,0
1917,1,0.030004,-0.013161,-0.012777,-0.019702,-0.019132,-0.014669,-0.024169,1,-0.116635,-0.027968,-0.004704,0,1
1918,0,0.005669,0.016410,0.016794,0.013494,0.014003,0.024221,0.053065,1,-0.051699,-0.074122,-0.006032,1,0
1919,0,0.001273,0.000876,0.001260,-0.002710,-0.002172,-0.003110,-0.000323,1,-0.025725,-0.089506,-0.006032,1,0
1920,0,-0.006861,0.001311,0.001695,0.000768,0.001300,-0.004586,-0.008412,1,-0.155596,-0.104891,-0.000573,1,0
1921,0,-0.015810,-0.007095,-0.006711,-0.008950,-0.008400,-0.003326,-0.006443,1,0.052197,0.110494,-0.000056,1,0
1922,0,-0.000979,0.006998,0.007382,0.007121,0.007641,0.011978,0.029150,1,0.000249,-0.027968,-0.006032,1,0
1923,0,-0.013959,0.005719,0.006103,-0.008698,-0.008148,-0.008187,-0.010241,1,-0.064686,0.033571,-0.006032,1,0
1924,0,-0.008378,-0.002789,-0.002405,-0.002807,-0.002268,-0.002101,0.001646,1,0.104145,0.218186,-0.006032,1,0
1925,0,-0.014674,-0.004567,-0.012983,-0.008582,-0.019000,-0.014564,-0.022699,1,0.000249,0.048955,-0.006032,1,0
1926,0,-0.005178,0.002140,0.002524,-0.002838,-0.002299,-0.001669,-0.003854,1,-0.025725,-0.089506,0.000622,1,0
1927,0,-0.010076,-0.003452,-0.003069,-0.006783,-0.006237,-0.006026,-0.010663,1,-0.129622,-0.058737,-0.001163,1,0
1928,0,-0.003953,-0.000669,-0.000285,-0.002720,-0.002181,-0.003470,-0.001027,1,0.052197,0.095109,-0.006032,1,0
1929,0,-0.007452,-0.001025,-0.000642,0.004332,0.004857,-0.001561,-0.003686,1,0.078171,0.218186,0.000667,1,0
1930,0,-0.000682,-0.008742,-0.008358,0.008847,0.009364,0.028362,0.043077,1,0.195054,0.156648,0.012929,1,0
1931,0,-0.012700,-0.000050,0.000334,-0.002703,-0.002165,-0.003254,-0.006330,1,-0.025725,0.033571,-0.000027,1,0
1932,0,-0.008327,0.001255,0.001639,0.001532,0.002062,0.009097,0.012971,1,0.065184,-0.027968,0.005034,1,0

In [75]:
nb=MultinomialNB()
train_d = pd.get_dummies(train)
nb.fit(train_d,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [76]:
train_d

,Bid_class,Claim_price,Total_land_real_area,Total_land_auction_area,Total_building_area,Total_building_auction_area,Total_appraisal_price,Minimum_sales_price,addr_do,Total_floor,Current_floor,Hammer_price,Diff_price,addr_san_N,addr_san_Y
0,1,1766037301,37.35,37.35,181.77,181.77,836000000,668800000,0,45,5,760000000,167200000,1,0
1,0,152946867,18.76,18.76,118.38,118.38,1073000000,858400000,0,70,51,971889999,214600000,1,0
2,1,11326510,71.00,71.00,49.94,49.94,119000000,76160000,0,15,14,93399999,42840000,1,0
3,0,183581724,32.98,32.98,84.91,84.91,288400000,230720000,0,20,11,256899000,57680000,1,0
4,0,45887671,45.18,45.18,84.96,84.96,170000000,136000000,0,7,7,158660000,34000000,1,0
5,0,105437195,41.39,41.39,84.46,84.46,222000000,177600000,0,20,17,206989000,44400000,1,0
6,0,137548730,81.77,81.77,112.70,112.70,188000000,120320000,0,6,6,135500000,67680000,1,0
7,0,506916971,92.22,92.22,243.35,243.35,667000000,533600000,0,24,13,640299999,133400000,1,0
8,0,40782876,66.44,66.44,67.21,67.21,94000000,75200000,0,3,1,77380000,18800000,1,0
9,0,150000000,78.52,78.52,84.92,84.92,163000000,130400000,0,5,4,177070000,32600000,1,0
10,1,500000000,18.27,18.27,81.96,81.96,299000000,239200000,0,15,12,240000001,59800000,1,0
11,0,37122950,37.38,37.38,84.72,84.72,241000000,192800000,0,15,2,221017200,48200000,1,0
12,0,25000000,31.69,7.04,84.60,18.80,41000000,26240000,0,22,11,31888000,14760000,1,0
13,0,135000000,0.00,0.00,106.34,106.34,560000000,448000000,0,39,5,518800000,112000000,1,0
14,0,953680000,80.62,80.62,182.76,182.76,669000000,669000000,0,28,26,670190000,0,1,0
15,0,13848484,53.84,53.84,150.80,150.80,604000000,483200000,0,31,8,531100000,120800000,1,0
16,0,149393725,25.70,25.70,74.45,74.45,165000000,105600000,0,21,1,143999000,59400000,1,0
17,1,1046685025,7.59,7.59,43.63,43.63,160000000,128000000,0,14,12,133000000,32000000,1,0
18,0,42479480,41.69,41.69,83.84,83.84,149000000,119200000,0,9,4,126651100,29800000,1,0
19,0,30665922,39.43,39.43,62.97,62.97,90000000,72000000,0,6,5,73899900,18000000,1,0
20,0,160000000,5.66,5.66,53.29,53.29,206000000,206000000,0,29,25,206119000,0,1,0
21,0,45589041,30.87,15.44,59.99,30.00,63000000,50400000,0,10,9,60299000,12600000,1,0
22,0,122134370,20.60,20.60,59.67,59.67,145000000,116000000,0,12,2,136630000,29000000,1,0
23,0,19800000,39.80,39.80,117.59,117.59,352000000,281600000,0,19,1,362000000,70400000,1,0
24,0,122663013,17.93,17.93,49.78,49.78,151000000,120800000,0,9,6,122000000,30200000,1,0
25,0,120000000,18.41,18.41,124.26,124.26,354000000,354000000,0,35,22,371131000,0,1,0
26,0,311657509,59.64,59.64,138.56,138.56,350000000,280000000,0,16,9,342750000,70000000,1,0
27,0,135600000,31.77,31.77,84.72,84.72,192000000,153600000,0,16,4,173711110,38400000,1,0
28,0,51975561,74.49,74.49,84.99,84.99,354000000,283200000,0,10,2,342525000,70800000,1,0
29,1,1087000000,16.65,16.65,98.08,98.08,228745632,117118000,0,15,8,126630000,111627632,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,0,179747997,40.52,40.52,84.15,84.15,334000000,267200000,1,15,5,301554999,66800000,1,0
1904,0,414554884,40.34,40.34,84.81,84.81,670000000,670000000,1,33,6,683800000,0,1,0
1905,0,1107295474,123.04,123.04,164.45,164.45,1600000000,1280000000,1,15,8,1605699900,320000000,1,0
1906,0,200000000,33.06,3.67,177.62,19.74,111000000,71040000,1,19,11,92100000,39960000,1,0
1907,0,62619025,25.47,4.63,39.84,7.24,38100000,30480000,1,12,2,36300000,7620000,1,0
1908,0,290729614,49.97,49.97,113.51,113.51,500000000,400000000,1,18,9,510000000,100000000,1,0
1909,0,386591869,40.27,40.27,84.94,84.94,594000000,594000000,1,20,6,660530000,0,1,0
1910,0,2000000000,108.25,108.25,134.49,134.49,1540000000,1540000000,1,18,2,1561800000,0,1,0
1911,0,56320487,78.55,8.73,130.93,14.55,94000000,75200000,1,14,3,91300000,18800000,1,0
1912,0,357918375,60.13,60.13,121.27,121.27,940000000,752000000,1,9,2,920500000,188000000,1,0
1913,0,390208900,58.09,58.09,84.65,84.65,470000000,376000000,1,10,6,444266000,94000000,1,0
1914,0,200000,46.71,46.71,114.34,114.34,643000000,514400000,1,6,4,660015000,128600000,1,0
1915,0,340000000,43.05,10.89,84.79,21.44,96000000,96000000,1,13,2,101600000,0,1,0
1916,0,140000000,27.01,27.01,56.82,56.82,182000000,145600000,1,6,3,171220000,36400000,1,0
1917,1,1056427163,7.25,7.25,12.77,12.77,90000000,72000000,1,8,7,83699000,18000000,0,1
1918,0,500000000,86.08,86.08,153.71,153.71,1170000000,1170000000,1,13,4,1200000000,0,1,0
1919,0,399507027,44.67,44.67,84.91,84.91,411000000,411000000,1,15,3,432700000,0,1,0
1920,0,213523555,45.83,45.83,99.68,99.68,370000000,296000000,1,5,2,337180000,74000000,1,0
1921,0,8901332,23.42,23.42,58.42,58.42,405000000,324000000,1,21,16,400100000,81000000,1,0
1922,0,348000000,60.99,60.99,126.65,126.65,830000000,830000000,1,17,7,832100000,0,1,0
1923,0,51228630,57.58,57.58,59.49,59.49,270000000,270000000,1,12,11,300015000,0,1,0
1924,0,178831561,34.90,34.90,84.50,84.50,439000000,439000000,1,25,23,453616100,0,1,0
1925,0,34880583,30.16,6.70,59.98,13.33,92900000,92900000,1,17,12,95655000,0,1,0
1926,0,252000000,48.04,48.04,84.37,84.37,451000000,360800000,1,15,3,455588000,90200000,1,0
1927,0,140000000,33.13,33.13,67.62,67.62,330000000,264000000,1,7,5,295899500,66000000,1,0
1928,0,280000000,40.55,40.55,84.87,84.87,401000000,401000000,1,21,15,402500000,0,1,0
1929,0,200000000,39.60,39.60,114.81,114.81,454000000,363200000,1,23,23,430234600,90800000,1,0
1930,0,354805459,19.03,19.03,133.98,133.98,1285000000,1028000000,1,32,19,1118999990,257000000,1,0
1931,0,80000000,42.20,42.20,84.94,84.94,407000000,325600000,1,15,11,403000000,81400000,1,0
1932,0,180000000,45.68,45.68,102.92,102.92,750000000,600000000,1,22,7,686010000,150000000,1,0

In [77]:
train_d=np.array(train_d)

In [78]:
fivefold(train_d,y,nb)

학습 accuacy = 0.50000000, 검증 accuacy = 0.54263566
학습 accuacy = 0.50388098, 검증 accuacy = 0.51421189
학습 accuacy = 0.51228978, 검증 accuacy = 0.52196382
학습 accuacy = 0.51712993, 검증 accuacy = 0.49222798
학습 accuacy = 0.51648352, 검증 accuacy = 0.49222798
평균 train accuacy : 0.5099568417276354
평균 test accuacy : 0.5126534656116533

In [79]:
# 나이브 베이지의 정확도는 좋지 않은 편이다.
# svm, 로지스틱, knn, 나이브베이지 모델을 적용해본 결과 svm을 사용한 모델이 가장 정확도가 높았다.